---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-volume
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-sc-cinderplugin-ceph
  resources:
    requests:
      storage: 1Gi
