---

apiVersion: v1
data:
  password: YmFy
  postgres-password: Zm9vYmFyMDAwMA==
kind: Secret
metadata:
  name: kong-postgresql
  namespace: kong
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "kong"
    meta.helm.sh/release-namespace: "kong"
